[profile.default]
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [{ access = "read-write", path = "./" }]
ffi = true
ast = true
build_info = true
extra_output = ["storageLayout"]
allow_internal_expect_revert = true


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
