[profile.default]
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [{ access = "read-write", path = "./" }]
ffi = true
ast = true
build_info = true
extra_output = ["storageLayout"]
allow_internal_expect_revert = true
[fmt]
line_length = 100
tab_width = 4
bracket_spacing = false
int_types = "long"
quote_style = "double"
number_underscore = "preserve"
single_line_statement_blocks = "preserve"
multiline_func_header = "all"
[lint]
exclude_lints = ["mixed-case-variable"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
