[package]
name = "chain-manager"
edition.workspace = true
license.workspace = true
authors.workspace = true
exclude.workspace = true
version.workspace = true

[dependencies]

[lints]
workspace = true
